### PR TITLE
chore: fix import order and whitespaces

### PR DESCRIPTION
**Pull request by keturn**
Update (Nov 29, 2023):
This PR was originally intended to correct the package association of inventory classes.
The majority of these changes was done in a similar way in https://github.com/Terasology/Inventory/pull/40.
What's left is whitespace and import order corrections.

---

Original PR description:

When I went to check on this module's test failures, I discovered its packages had accidentally been moved in to the `org.terasology.engine` namespace during the migration.

This PR corrects that, but I'm afraid there are probably lots of downstream modules that use InventoryComponent that will also need correcting.

### CODE REVIEW

**Comment by keturn** [comment]
it might well be worth doing #37 at the same time, since we have to update all the dependents either way.

**Comment by keturn** [comment]
four other modules were similarly effected, so we'll probably want to clean them up as a batch. https://github.com/MovingBlocks/Terasology/issues/4571

**Comment by soloturn** [comment]
this can be closed @jdrueckert @keturn ?

**Comment by jdrueckert** [comment]
> this can be closed @jdrueckert @keturn ?

why?

**Comment by jdrueckert** [comment]
The majority of the originally intended changes was done in a similar way in https://github.com/Terasology/Inventory/pull/40.
With this, the remaining changes only concern whitespaces and imports.
I'm changing the PR title and description. We definitely should squash-merge this to avoid confusion.

**Review by jdrueckert — APPROVED** [review]

**Pull request merged**
