### PR TITLE
refactor: address IntelliJ QAPlug plugin findings

### PR DESCRIPTION
**Pull request by jdrueckert**
* remove unused imports
* remove unnecessary if statement nesting
* remove redundant public modifier

Relates to https://github.com/MovingBlocks/Terasology/pull/5149

### CODE REVIEW

**Review by soloturn — DISMISSED** [review]

**Comment by jdrueckert** [comment]
@soloturn thanks for the approval! I need to sort out our GitHub teams so that you can actually approve 🙈

**Comment by soloturn** [comment]
@jdrueckert i would really appreciate if you merge this one or get it merged.

**Review by soloturn — APPROVED** [review]

**Comment by soloturn** [comment]
seems approve worked thank you @jdrueckert . but merge button is not active. is it for you?

**Comment by jdrueckert** [comment]
> seems approve worked thank you @jdrueckert . but merge button is not active. is it for you?

It is not active for me either which is due to the fact that the pipeline hasn't passed.
Our `develop` branches are protected. In order to merge a PR to them, the PR needs to be approved and pass the checks.
Only administrators can bypass these branch protections.

Now that we have our module pipelines set up again (after our recent CI changes), we can run the pipeline again and if it passes - which I'm expecting it to do - we can go ahead and merge.

**Pull request merged**
