### PR TITLE
fix: fix compilation with Gestalt 8

### PR DESCRIPTION
**Pull request by BenjaminAmos**
This pull request contains fixes to ensure that the module compiles under Gestalt 8.

This depends on MovingBlocks/Terasology#5267.

### CODE REVIEW

**Review by soloturn — DISMISSED** [review]
not sure what the error means:
package org.terasology.context.annotation

as it would not compile if this would not exist.

**Comment by soloturn** [comment]
should the version be updated to 2.0.0 ?

**Comment by BenjaminAmos** [comment]
This change would increase the minimum engine version needed, so it may be a breaking change that warrants a new major version. It all depends on the perspective that you version modules from (module API vs jar ABI vs source API). I am not entirely sure at the moment.

**Comment by jdrueckert** [comment]
> not sure what the error means: package org.terasology.context.annotation
> as it would not compile if this would not exist.

@soloturn This seems to be a GitHub check report caching issue in the "Files changed" view...
If you click on the check run associated with the warning, you'll see that this ran 5 days ago (probably before the "publish" stage of the engine merge job was done). If you refresh to a later run, you'll see that the warning are gone.

> This change would increase the minimum engine version needed, so it may be a breaking change that warrants a new major version. It all depends on the perspective that you version modules from (module API vs jar ABI vs source API). I am not entirely sure at the moment.

@BenjaminAmos We currently do not have a true notion of "module version abc depends on engine version xyz". Changing this is a bigger effort that we (IMO) should tackle in the future, but I don't think the time for that is now. Currently, module versions communicate changes that are visible to the player. This is no such change, so it shouldn't be a minor or major version bump. We can do a patch bump though, if we want, to indicate that something in the background technically works differently.

**Review by jdrueckert — APPROVED** [review]

**Pull request merged**
